{
 "title": "Node Exporter Basic",
 "panels": [
  {
   "title": "CPU Usage - controlplane",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", nodename=\"k8scontrolplain\"}[$__rate_interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage - worker1",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", nodename=\"k8sworker1\"}[$__rate_interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage - worker2",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", nodename=\"k8sworker2\"}[$__rate_interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Usage - worker3",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\", nodename=\"k8sworker3\"}[$__rate_interval])) * 100)"
    }
   ]
  }
 ]
}