apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        monitoring: prod

      serviceAccountName: prometheus

      containers:
        - name: prometheus
          image: prom/prometheus:latest

          securityContext:
            runAsUser: 0   # had no root permissions fixed here

          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/data"
            - "--storage.tsdb.retention.time=12h"

          ports:
            - containerPort: 9090

          resources:
            requests:
              memory: "250Mi"
              cpu: "150m"
            limits:
              memory: "500Mi"
              cpu: "300m"

          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /prometheus/data  ## issue prom wants to access this folder so i set it here

      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
