apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  namespace: prod
spec:
  serviceName: mysql-master
  replicas: 1

  selector:
    matchLabels:
      app: mysql-master

  template:
    metadata:
      labels:
        app: mysql-master
        role: master   # HA for SQL
    spec:
      nodeSelector:
        env: prod

      affinity: # for better pod distrebution
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mysql-master
                      - mysql-slave
              topologyKey: "kubernetes.io/hostname"

      containers:
        - name: mysql
          image: mysql:8.0

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE

          ports:
            - containerPort: 3306

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d

      volumes:
        - name: mysql-config
          configMap:
            name: mysql-master-config

  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi