apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring-prod
spec:
  replicas: 1   # set to 1 regarding PVC RWO
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        monitoring: prod
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: grafana
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000

          # Secret login -> see configmap
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-password

          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          volumeMounts:
            - name: grafana-config-volume
              mountPath: /etc/grafana
            - name: grafana-storage
              mountPath: /var/lib/grafana   # had wrong folder path fixed now

      volumes:
        - name: grafana-config-volume
          configMap:
            name: grafana-config
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc