name: Deploy Monitoring (PROD)

on:
  workflow_dispatch:

jobs:
  deploy-monitoring:
    runs-on: [self-hosted, Linux, X64, k8s]

    steps:
      - uses: actions/checkout@v4

      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Set prod context
        run: |
          kubectl config use-context kubernetes-admin-prod

      - name: Debug #might be unecessary
        run: |
          kubectl config get-contexts
          kubectl config current-context

      - name: Verify cluster connection
        run: |
          kubectl get nodes

      - name: Apply monitoring manifests
        run: |
          kubectl apply -f k8s/monitoring -n monitoring-prod

      - name: Restart monitoring deployments
        run: |
          kubectl get deployments -n monitoring-prod -o name \
            | xargs -n1 kubectl rollout restart -n monitoring-prod

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment -n monitoring-prod --timeout=180s

      - name: Verify pods
        run: |
          kubectl get pods -n monitoring-prod -o wide
